repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      # 1) Nur Imports sortieren (I001 / I)
      - id: ruff-check
        name: ruff (sort imports)
        args: ["--select", "I", "--fix"]

      # 2) Rest lint/fix
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]

      # 3) Formatter zuletzt
      - id: ruff-format
